---
# This playbook contains common plays that will be run on all nodes.

- name: Update apt-get
  apt: update_cache=yes

- name: Install ntp 
  apt: name=ntp state=present
  tags: ntp

- name: Configure ntp file
  template: src=ntp.conf.j2 dest=/etc/ntp.conf
  tags: ntp
  notify: restart ntp

- name: Start the ntp service
  service: name=ntp state=started enabled=true
  tags: ntp

- name: Install git
  apt: name=git state=latest
  tags: git
